### ISSUE TITLE
Generic method call

### ISSUE THREAD

**Issue by juliaanduchateau** [Maroder1/TIA-openness#1]
Hi there

I'm trying building a tool to manipulate the hmi screen. I use dotSeeker to examine the DLL file.
I can now connect to TIA Portal, open a project and find the hmi device. But I need the DeviceImpl (Siemens.Engineering.HW.DeviceImpl) to return a SoftwareContainer object (Siemens.Engineering.HW.Features.SoftwareContainer). I think I can use the generic GetService<T>() method, but I'm not sure how to call the method in Python.

When I call GetService() on the DeviceImpl object, I get:
```
InvalidOperationException                 Traceback (most recent call last)
<ipython-input-19-7da148171f19> in <module>
----> 1 hmidevice.GetService()

InvalidOperationException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Python.Runtime.MethodBinder.Invoke(IntPtr inst, IntPtr args, IntPtr kw, MethodBase info, MethodInfo[] methodinfo)
```
When I call GetService(Siemens.Engineering.HW.Features.SoftwareContainer), I get:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-20-bd0ec11397c7> in <module>
----> 1 hmidevice.GetService(tia.HW.Features.SoftwareContainer)

TypeError: No method matches given arguments for GetService
```

Do you know how to call this generic method in Python?

**Comment by Maroder1** [comment]
I haven't tested that out, but should be similar?
`network_service = tia.IEngineeringServiceProvider(deviceitem).GetService[hwf.NetworkInterface]()`

I made another repo  public where I am testing some more, where I use the above in context. 
you should find it in "In [6]" in the jupyter notebook: https://github.com/Maroder1/pyopenness.git

Let me know if it works out or not and I'll check your specific case.

EDIT: you might find dir() useful to explore objects/the api. Especially if you use jupyter as it is very quick to test & check
